# /wikiで表示されるリンクを設定します
URL: "https://github.com/"
# 登録したURLの一覧
# デフォルト
# message:
#   GitHub:
#     URL: https://github.com/
message:
  GitHub:
    URL: https://github.com/
# TAB補完に表示されるリスト
# messageで設定した名前と同じにしてください
# 表示したくない場合はその文字列を削除してください
#TAB:
#  - 'GitHub'
TAB:
  - 'GitHub'
