name: Wikipebia
version: '${version}'
main: com.github.albardoo02.Wikipebia
api-version: 1.15
authors: [ albardoo02 ]
description: Wikiコマンド

commands:
  wiki:
    aliases:
      - wk
      - wikipebia

permissions:
  wikipebia.*:
    children:
      wikipebia.command.admin: true
      wikipebia.command.member: true
    default: op
  wikipebia.command.admin:
    default: op
  wikipebia.command.member:
    default: op